#!/usr/bin/env python3
"""
generate_bootloader_header.py

Compresses the Papilio Tang bootloader FPGA bitstream using raw deflate and
writes a C header containing the compressed bytes as a static uint8_t array.
The header is included by ota_server.c and streamed to the FPGA SRAM via JTAG
before every SPI-flash update, eliminating the need for a pre-flashed bootloader.

Usage (from FPGA-Companion repo root):
    python generate_bootloader_header.py
    python generate_bootloader_header.py <input.bin> <output.h>

Defaults:
    input  : ../papilio_tang_bootloader/fpga/impl/pnr/project.bin
    output : src/esp32/bootloader_data.h
"""

import sys
import os
import zlib


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))

    input_path = (sys.argv[1] if len(sys.argv) >= 2 else
                  os.path.join(script_dir, '..', 'papilio_tang_bootloader',
                               'fpga', 'impl', 'pnr', 'project.bin'))
    output_path = (sys.argv[2] if len(sys.argv) >= 3 else
                   os.path.join(script_dir, 'src', 'esp32', 'bootloader_data.h'))

    input_path  = os.path.abspath(input_path)
    output_path = os.path.abspath(output_path)

    if not os.path.isfile(input_path):
        print(f"ERROR: Input file not found: {input_path}", file=sys.stderr)
        sys.exit(1)

    print(f"Input  : {input_path}")
    print(f"Output : {output_path}")

    with open(input_path, 'rb') as f:
        data = f.read()

    # Raw deflate — no zlib/gzip wrapper.
    # Decompressed on-device with tinfl in ring-buffer mode (flags=0).
    compress_obj = zlib.compressobj(level=9, method=zlib.DEFLATED, wbits=-15)
    compressed   = compress_obj.compress(data) + compress_obj.flush()

    ratio = len(compressed) / len(data) * 100
    print(f"Original   : {len(data):,} bytes")
    print(f"Compressed : {len(compressed):,} bytes  ({ratio:.1f}% of original)")

    # Build hex lines (16 bytes per line)
    hex_lines = []
    for i in range(0, len(compressed), 16):
        chunk = compressed[i:i + 16]
        hex_lines.append('    ' + ', '.join(f'0x{b:02x}' for b in chunk) + ',')

    with open(output_path, 'w', newline='\n') as f:
        f.write(
            f"/*\n"
            f" * bootloader_data.h — embedded Papilio Tang bootloader bitstream\n"
            f" *\n"
            f" * Auto-generated by generate_bootloader_header.py\n"
            f" * DO NOT EDIT — regenerate from project.bin:\n"
            f" *   python generate_bootloader_header.py\n"
            f" *\n"
            f" * Source     : {os.path.basename(input_path)}\n"
            f" * Original   : {len(data)} bytes\n"
            f" * Compressed : {len(compressed)} bytes (raw deflate, level 9)\n"
            f" */\n"
            f"#pragma once\n"
            f"\n"
            f"#include <stdint.h>\n"
            f"#include <stddef.h>\n"
            f"\n"
            f"/* Uncompressed size of the bootloader bitstream (bytes) */\n"
            f"#define BOOTLOADER_UNCOMPRESSED_SIZE  {len(data)}U\n"
            f"\n"
            f"/* Size of the compressed array below (bytes) */\n"
            f"#define BOOTLOADER_COMPRESSED_SIZE    {len(compressed)}U\n"
            f"\n"
            f"/* Raw-deflate compressed bitstream (wbits=-15, level 9).\n"
            f" * Decompress with tinfl ring-buffer mode (flags=0). */\n"
            f"static const uint8_t bootloader_compressed_data[BOOTLOADER_COMPRESSED_SIZE] = {{\n"
        )
        f.write('\n'.join(hex_lines))
        f.write('\n};\n')

    print(f"Written    : {output_path}")


if __name__ == '__main__':
    main()


if __name__ == '__main__':
    main()
